### ISSUE TITLE
FakeVim doesn't work?

### ISSUE THREAD

**Issue by linxd5** [hluk/FakeVim#33] opened 2015-11-04 06:50 UTC
Hello, My ReText version is 5.2.1 (using PyMarkups 0.6.1), and FakeVim doesn't work ~   below is my configuration file:

 [General]
autoSave=true
highlightCurrentLine=true
previewState=true
restorePreviewState=true
saveWindowGeometry=true
spellCheck=true
useFakeVim=true
useWebKit=true
windowGeometry="@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x3\xe\0\0\0\xef\0\0\a\xa1\0\0\x4;\0\0\x3\x18\0\0\x1\x15\0\0\a\x97\0\0\x4\x31\0\0\0\0\0\0\0\0\a\x80)"

Thank you~

**Comment by hluk** [comment] 2015-11-05 07:48
Closing as duplicate of #32.

**Closed by hluk** 2015-11-05 07:48 UTC
